# --- State untuk ConversationHandler ---

# State Pengguna
(
    STATE_PHOTO,
    STATE_PET_FORMAT,
    STATE_USER_TELE,
    STATE_WAITING_PAYMENT,
    # --- Alur Edit dari Riwayat ---
    STATE_EDIT_CHOICE,
    STATE_EDIT_DESC,
    STATE_EDIT_USER,
    # --- Alur Edit dari Konfirmasi Final ---
    STATE_FINAL_CONFIRM,
    STATE_EDIT_PHOTO_CONFIRM,
    STATE_EDIT_DESC_CONFIRM,
    STATE_EDIT_USER_CONFIRM,
    STATE_WAITING_PACKAGE_PAYMENT
) = range(12)

# State Admin
(
    STATE_ADMIN_GET_USER_INPUT,
    STATE_ADMIN_GET_SUBMISSION_ID,
    STATE_ADMIN_GET_BROADCAST_MSG,
    STATE_ADMIN_GET_REDUCE_AMOUNT,
    STATE_ADMIN_SEARCH_USER_INPUT,
    STATE_ADMIN_GET_TICKET_AMOUNT,
    STATE_ADMIN_EDIT_DESC_INPUT,
    STATE_ADMIN_EDIT_TELE_INPUT,
    STATE_ADMIN_CHOOSE_PKG_TYPE,
    STATE_ADMIN_GET_EDIT_AMOUNT,
    STATE_ADMIN_SEARCH_USER_INPUT,
    STATE_ADMIN_CONFIRM_EDIT
) = range(11, 23)